### ISSUE TITLE
Food ontology API

### ISSUE THREAD

**Issue by mischkew** [mischkew/food-hack#10]

**Comment by aleximmer** [comment]
We have different API options, depending on what we want to search for. Unfortunately I couldn't find a database we could use for free except for DBpedia, which we should definitely try out. Apart from spoonacular there are the following options which looked good and also provided similar search options:
- [Edamam](https://developer.edamam.com/edamam-docs-recipe-api])
- [Food2Fork](http://food2fork.com/about/api)
- [Yummly](https://developer.yummly.com/documentation#Attribution)
- [BigOven](http://api2.bigoven.com/)

The second has a nice free contingent while the others don't. Indeed Edamam and Yummly provide more information and contain ratings and selected images which is nice but not worth paying initially.

We should use one of the following
- free spoonacular (25 requests, 1k classifications)
- free Food2Fork (500 recipe-searches/day)
- DBpedia (not confirmed that this is a nice idea 😄 )

**Comment by mischkew** [comment]
Issue moved to [NeighborhoodCuisine/neighborhood-cuisine #6](https://github.com/NeighborhoodCuisine/neighborhood-cuisine/issues/6) via [**ZenHub.io**](https://www.zenhub.io/)
