### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by mischkew** [mischkew/food-hack#11]

**Comment by aleximmer** [comment]
Repo owner has to activate, @mischkew ;)

**Comment by mischkew** [comment]
@AlexImmer which one?
travis?

**Comment by aleximmer** [comment]
yes!

**Comment by mischkew** [comment]
i added CI. can you configure it?

**Comment by mischkew** [comment]
Issue moved to [NeighborhoodCuisine/neighborhood-cuisine #5](https://github.com/NeighborhoodCuisine/neighborhood-cuisine/issues/5) via [**ZenHub.io**](https://www.zenhub.io/)
