### ISSUE TITLE
Create Chatbot

### ISSUE THREAD

**Issue by aleximmer** [mischkew/food-hack#14]
- [ ] ingredients parsen, abfragen
- [ ] für mehrere nutzer
- [ ] auswahl an recipes zurückgeben und darstellen
- [ ] fehlende ingredients anzeigen

**Comment by mischkew** [comment]
Issue moved to [NeighborhoodCuisine/neighborhood-cuisine #2](https://github.com/NeighborhoodCuisine/neighborhood-cuisine/issues/2) via [**ZenHub.io**](https://www.zenhub.io/)
