### ISSUE TITLE
Backend recipe search

### ISSUE THREAD

**Issue by aleximmer** [mischkew/food-hack#15]
search top 5 recipes based on a list of given ingredients such. Metrics not yet defined

given: list of ingredients
return: 5 recipes sorted with image, explicit missing ingredients

**Comment by mischkew** [comment]
Issue moved to [NeighborhoodCuisine/neighborhood-cuisine #1](https://github.com/NeighborhoodCuisine/neighborhood-cuisine/issues/1) via [**ZenHub.io**](https://www.zenhub.io/)
