### ISSUE TITLE
Persistent User Storage

### ISSUE THREAD

**Issue by mischkew** [mischkew/food-hack#2]

**Comment by aleximmer** [comment]
Definitely a document storage to avoid migration when changing models etc. 
I would start using a mongoDB instance.

**Comment by mischkew** [comment]
Issue moved to [NeighborhoodCuisine/neighborhood-cuisine #8](https://github.com/NeighborhoodCuisine/neighborhood-cuisine/issues/8) via [**ZenHub.io**](https://www.zenhub.io/)
