### ISSUE TITLE
Decide language and host for backend

### ISSUE THREAD

**Issue by mischkew** [mischkew/food-hack#3]

**Comment by aleximmer** [comment]
Cropped the decision down to 2 languages after looking at AWS services and used languages for different use cases. There is not yet an advantage of one over the other respectively:
- Nodejs
- Python (Flask)

Both can be scaled (Django/flask for python and Express for node) using aws services and other available hosting solutions. I expected node to scale better but it does not seem to be the case. Thus I will stay with python for now.
