### ISSUE TITLE
notifications

### ISSUE THREAD

**Issue by mischkew** [mischkew/food-hack#7]

**Comment by aleximmer** [comment]
Foudn something nice: https://medium.com/@DannyvanderJagt/how-to-use-push-notifications-in-react-native-41e8b14aadae#.v5xyl5ps1
Notifications go through apple servers but appear to be working with react which is nice 👍

**Comment by mischkew** [comment]
Issue moved to [NeighborhoodCuisine/neighborhood-cuisine #7](https://github.com/NeighborhoodCuisine/neighborhood-cuisine/issues/7) via [**ZenHub.io**](https://www.zenhub.io/)
